// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsaQCHbiKum1GLC1Yl-rqJVXsIQrLfwyo',
    appId: '1:482480321873:ios:dc451d7e9cea5e1a1e8f70',
    messagingSenderId: '482480321873',
    projectId: 'trypx-app',
    storageBucket: 'trypx-app.firebasestorage.app',
    iosClientId: '482480321873-djo33rk962v8e4imgi6rg18s2vsamtv0.apps.googleusercontent.com',
    iosBundleId: 'com.tripstream.trypx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKNUBUuxYD2-I9aGSzhRbJXyUcdrIY0ts',
    appId: '1:482480321873:web:b120a9d7a07de56a1e8f70',
    messagingSenderId: '482480321873',
    projectId: 'trypx-app',
    authDomain: 'trypx-app.firebaseapp.com',
    storageBucket: 'trypx-app.firebasestorage.app',
    measurementId: 'G-Y5NPG9WZRM',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKNUBUuxYD2-I9aGSzhRbJXyUcdrIY0ts',
    appId: '1:482480321873:web:b120a9d7a07de56a1e8f70',
    messagingSenderId: '482480321873',
    projectId: 'trypx-app',
    authDomain: 'trypx-app.firebaseapp.com',
    storageBucket: 'trypx-app.firebasestorage.app',
    measurementId: 'G-Y5NPG9WZRM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsaQCHbiKum1GLC1Yl-rqJVXsIQrLfwyo',
    appId: '1:482480321873:ios:dc451d7e9cea5e1a1e8f70',
    messagingSenderId: '482480321873',
    projectId: 'trypx-app',
    storageBucket: 'trypx-app.firebasestorage.app',
    iosClientId: '482480321873-djo33rk962v8e4imgi6rg18s2vsamtv0.apps.googleusercontent.com',
    iosBundleId: 'com.tripstream.trypx',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjxnREYW9Y1wzhk1ODLXW4h7TVeMmgWSY',
    appId: '1:482480321873:android:487455f450fb49d31e8f70',
    messagingSenderId: '482480321873',
    projectId: 'trypx-app',
    storageBucket: 'trypx-app.firebasestorage.app',
  );
}
